//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovoriLegko
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int ID_Клиента { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Expr7 { get; set; }
        public Nullable<System.DateTime> Expr8 { get; set; }
        public string Expr9 { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Номер_телефона { get; set; }
        public string Expr10 { get; set; }
        public string Expr11 { get; set; }
        public int ID_Сотрудника { get; set; }
        public string Expr4 { get; set; }
        public string Должность { get; set; }
    }
}
