//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovoriLegko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группа()
        {
            this.Распределение = new HashSet<Распределение>();
            this.Уроки = new HashSet<Уроки>();
        }
    
        public int ID_Группы { get; set; }
        public Nullable<int> ID_Сотрудника { get; set; }
        public string Название { get; set; }
        public string Количество_человек { get; set; }
        public Nullable<System.DateTime> Дата_начала_занятия { get; set; }
        public Nullable<System.DateTime> Дата_конца_занятия { get; set; }
        public string Предмет { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Распределение> Распределение { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Уроки> Уроки { get; set; }
    }
}
