//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovoriLegko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оплата
    {
        public int ID_Оплата { get; set; }
        public Nullable<int> ID_Представитель { get; set; }
        public string Сумма { get; set; }
        public string Номер_карты { get; set; }
        public Nullable<System.DateTime> Дата_оплаты { get; set; }
        public string Номер_телефона { get; set; }
    
        public virtual Представитель Представитель { get; set; }
    }
}
