//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovoriLegko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Распределение
    {
        public int ID_Записи { get; set; }
        public Nullable<int> ID_Группы { get; set; }
        public Nullable<int> ID_Клиента { get; set; }
    
        public virtual Группа Группа { get; set; }
        public virtual Клиент Клиент { get; set; }
    }
}
