//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovoriLegko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Уроки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Уроки()
        {
            this.Посещаемость = new HashSet<Посещаемость>();
        }
    
        public int ID_Урока { get; set; }
        public Nullable<int> ID_Группы { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Начало { get; set; }
        public string Длительноть { get; set; }
    
        public virtual Группа Группа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посещаемость> Посещаемость { get; set; }
    }
}
